api/src/main/java/org/pentaho/metaverse/api/ILineageCollector.java, api/src/main/java/org/pentaho/metaverse/api/model/LineageRequest.java, core/src/main/java/org/pentaho/metaverse/impl/FileSystemLineageCollector.java, core/src/main/java/org/pentaho/metaverse/service/AnalyzerInfo.java, core/src/main/java/org/pentaho/metaverse/service/AnalyzerInfoService.java, core/src/main/java/org/pentaho/metaverse/service/LineageStreamingOutput.java, core/src/main/java/org/pentaho/metaverse/service/MetaverseService.java, core/src/main/java/org/pentaho/metaverse/util/DateRangeFolderFilenameFilter.java, core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, core/src/main/resources/com/pentaho/metaverse/messages/messages.properties, core/src/test/java/org/pentaho/metaverse/impl/FileSystemLineageCollectorTest.java, core/src/test/java/org/pentaho/metaverse/service/AnalyzerInfoServiceTest.java, core/src/test/java/org/pentaho/metaverse/service/AnalyzerInfoTest.java, core/src/test/java/org/pentaho/metaverse/service/LineageStreamingOutputTest.java, core/src/test/java/org/pentaho/metaverse/service/MetaverseServiceTest.java, core/src/test/java/org/pentaho/metaverse/util/DateRangeFolderFilenameFilterTest.java, core/src/test/resources/com/pentaho/metaverse/messages/messages.properties, core/src/test/resources/pentaho-lineage-output/20150706/repo/validation/merge_join.ktr/1436208018952_merge_join.execution.js, core/src/test/resources/pentaho-lineage-output/20150706/repo/validation/merge_join.ktr/1436208018952_merge_join.graphml, core/src/test/resources/pentaho-lineage-output/20150706/repo/validation/strings_cut.ktr/1436206662536_strings_cut.execution.js, core/src/test/resources/pentaho-lineage-output/20150706/repo/validation/strings_cut.ktr/1436206662536_strings_cut.graphml, core/src/test/resources/pentaho-lineage-output/20150707/repo/validation/merge_join.ktr/1436277809629_merge_join.execution.js, core/src/test/resources/pentaho-lineage-output/20150707/repo/validation/merge_join.ktr/1436277809629_merge_join.graphml
[BACKLOG-1336] - Create REST endpoints for access to lineage-related metadata
=> [BACKLOG-1336] - Create REST endpoints for access to lineage-related metadata

core/src/it/resources/repo/validation/jobentry-trans-executor/jobentry-trans-executor.kjb, core/src/it/resources/repo/validation/jobentry-trans-executor/logging_trans.ktr, core/src/it/resources/repo/validation/jobentry-trans-executor/rowgen_trans.ktr
Also removed unused DB connections
=> [TEST] Fixed broken integration test (paths were hardcoded)

core/enunciate.xml, core/pentaho.fmt, core/pom.xml, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/service/AnalyzerInfoService.java, core/src/main/java/org/pentaho/metaverse/service/MetaverseService.java
[BACKLOG-1336] - Adding API javadoc and associated enunciate build capabilities
enunciate now runs as part of the "assemble" goal. resulting doc is generated in core/target/enunciate/build/docs.
=> [BACKLOG-1336] - Adding API javadoc and associated enunciate build capabilities

api/src/main/java/org/pentaho/metaverse/api/model/JdbcResourceInfo.java, api/src/test/java/org/pentaho/metaverse/api/model/JdbcResourceInfoTest.java
@mdamour1976 @rfellows @mattyb149 please review
=> [BACKLOG-4190] JdbcResourceInfo: replace vars from dbMeta

core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPoint.java
Do not execute transFinish handler for trans run in preview
@rfellows please review along with https://github.com/pentaho/pentaho-kettle/pull/1578
=> [BACKLOG-4224] KettleVFS error after perform a Preview

core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobLineageHolderMap.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransLineageHolderMap.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/jobentry/job/JobJobEntryAnalyzer.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/jobentry/transjob/TransJobEntryAnalyzer.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/jobexecutor/JobExecutorStepAnalyzer.java
[BACKLOG-4116] - Fixes for JobEntry stuff when running on a di-repo
=> [BACKLOG-4116] - Fixes for JobEntry stuff when running on a di-repo

core/pom.xml
with those maintained by the build team.
@lucboudreau
=> [CLEANUP] making version properties consistent

core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransExtensionPointUtil.java
=> [BACKLOG-5180] Add support for repo-based lineage at design time (in Spoon)

core/pom.xml, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/BaseRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobLineageHolderMap.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransLineageHolderMap.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPoint.java, core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, core/src/main/resources/OSGI-INF/blueprint/pdi-plugins.xml, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/BaseRuntimeExtensionPointTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPointTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPointTest.java
@rfellows forward port of #386 to master
=> [BACKLOG-5308] Disable runtime lineage by default

core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPointTest.java
[BACKLOG-5308] [TEST] - Adding import to fix compile issue in JobRuntimeExtensionPointTest.
=> [BACKLOG-5308] [TEST] - Adding import to fix compile issue in JobRuntimeExtensionPointTest.

core/pom.xml
[TEST] - Adding in a test dependency that is no longer coming in transitively.
=> [TEST] - Adding in a test dependency that is no longer coming in transitively.

api/pom.xml, core/pom.xml, pom.xml, sample/pom.xml
should make the integration tests and sonar publishing work again
=> [CLEANUP] updates for new parent pom

core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/excelinput/ExcelInputExternalResourceConsumer.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/excelinput/ExcelInputStepAnalyzerTest.java
- look for StepMetaInterface in stepMeta, if it is not found in a current step directly.
- tests written and restructured
@mattyb149, @rfellows  review it please
=> [PDI-14665] Excel File Input crashes on 6.0 when fed zip file from previous step

core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/excelinput/ExcelInputExternalResourceConsumer.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/excelinput/ExcelInputStepAnalyzerTest.java
@rfellows review it please, This is a backport of #397
=> [SP-2299] Backport of PDI-14665 - Excel File Input crashes on 6.0 when fed zip file from previous step (6.0 Suite)

pom.xml
tested with http://cerberus.pentaho.com/job/master-snapshot/job/metaverse-plugin/112/console
published http://nexus.pentaho.org/content/sites/public-site/pentaho/pentaho-metaverse-6.1-SNAPSHOT/
=> [ENGOPS-1654] parent pom update for site pub and aggregation

core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/transexecutor/TransExecutorStepAnalyzerTest.java
=> [TEST] testCustomAnalyze_fileName() fixed with OS-independent pathSeparator

core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzer.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzerTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/transexecutor/TransExecutorStepAnalyzerTest.java
- Use output field names if database fields is not specified
- UTs
=> [PDI-14959] Data Lineage: Table Output step analyzer does not add default fields to the lineage output

core/pom.xml
only merge after https://github.com/pedrofvteixeira/pentaho-platform/tree/BACKLOG-12101 merge
=> [ENGOPS-2625] added classifier to platform-core test

core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/impl/FileSystemLineageCollector.java, core/src/main/java/org/pentaho/metaverse/impl/VfsLineageCollector.java, core/src/main/java/org/pentaho/metaverse/impl/VfsLineageWriter.java, core/src/main/java/org/pentaho/metaverse/util/VfsDateRangeFilter.java, core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, core/src/main/resources/com/pentaho/metaverse/messages/messages.properties, core/src/test/java/org/pentaho/metaverse/impl/VfsLineageCollectorTest.java, core/src/test/java/org/pentaho/metaverse/impl/VfsLineageWriterTest.java, core/src/test/java/org/pentaho/metaverse/util/VfsDateRangeFilterTest.java
=> [BACKLOG-11039] - Implemented VFS writer and collector for lineage.

core/src/main/java/org/pentaho/metaverse/impl/model/MongoDbResourceInfo.java, core/src/test/java/org/pentaho/metaverse/impl/model/MongoDbResourceInfoTest.java
* Fixed check for context name
=> [PDI-16022]-Test transformation fails with encrypted password in a parameter for "MongoDB Input" and "MongoDB Output" Steps

core/src/main/java/org/pentaho/metaverse/impl/model/MongoDbResourceInfo.java, core/src/test/java/org/pentaho/metaverse/impl/model/MongoDbResourceInfoTest.java
=> [SP-3382]-[PDI-16022]-Test transformation fails with encrypted password in a parameter for "MongoDB Input" and "MongoDB Output" Steps

.gitignore, pom.xml
=> [ENGOPS-3029] update parent pom version to 7.1-SNAPSHOT

core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPoint.java
=> [FIX BUILD]

api/pom.xml
DO NOT MERGE prior to merge of kettle mavenization!
=> [BACKLOG-12977] Exclude problematic transitive from kettle engine

api/src/main/java/org/pentaho/metaverse/api/model/IExecutionEngine.java
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
=> [ENGOPS-3650] change Pentaho to Hitachi Vantara and update copyright date

core/src/main/java/org/pentaho/metaverse/impl/VfsLineageWriter.java, core/src/test/java/org/pentaho/metaverse/impl/VfsLineageWriterTest.java
- added auto-close for output stream being created
=> [CLEANUP] fixed failed tests

core/pom.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
=> [ENGOPS-1757] version name consolidation

api/src/main/java/org/pentaho/dictionary/DictionaryConst.java, api/src/main/java/org/pentaho/dictionary/DictionaryHelper.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/BaseKettleMetaverseComponent.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/KettleAnalyzerUtil.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/ExternalResourceStepAnalyzer.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/StepAnalyzer.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/StepNodes.java, api/src/test/java/org/pentaho/dictionary/DictionaryHelperTest.java, api/src/test/java/org/pentaho/metaverse/api/analyzer/kettle/step/ExternalResourceStepAnalyzerTest.java, api/src/test/java/org/pentaho/metaverse/api/analyzer/kettle/step/StepNodesTest.java, core/src/main/java/org/pentaho/metaverse/impl/MetaverseBuilder.java
=> [BACKLOG-21736] Adding a data-lineage analyzer for the JSON Input step

api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/KettleAnalyzerUtil.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/BaseStepExternalResourceConsumer.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/ExternalResourceStepAnalyzer.java
=> [BACKLOG-21738] Adding a data-lineage analyzer for the JSON Output step

api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/ExternalResourceStepAnalyzer.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/StepAnalyzer.java, core/src/it/java/org/pentaho/metaverse/MetaverseValidationIT.java, core/src/it/resources/repo/validation/rest_client.ktr
Additionally, fixed a couple of other newly failing integration tests which started failing due to decoupling of the ConcatFields step from the kettle engine (unrelated to my work, and coincidental that these tests started failing now):
For reference, ConcatFields Decoupling commit: https://github.com/pentaho/pentaho-kettle/pull/5214/commits/60fd1df3893fd0ada33345e19288a4233b64f935
Related PR: https://github.com/pentaho/pentaho-kettle/pull/5217
@pentaho/r2d2
=> [BACKLOG-22731] Fix Stream Lookup analyzer and failing integration test

api/src/main/java/org/pentaho/dictionary/DictionaryConst.java, api/src/main/java/org/pentaho/dictionary/DictionaryHelper.java, api/src/test/java/org/pentaho/dictionary/DictionaryHelperTest.java, core/src/it/java/org/pentaho/metaverse/frames/RootNode.java, core/src/main/java/org/pentaho/metaverse/impl/MetaverseBuilder.java
=> [BACKLOG-22079] Removing unnecessary meta/entity nodes from the data-lineage graphml

core/src/it/java/org/pentaho/metaverse/MetaverseValidationIT.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/selectvalues/SelectValuesStepAnalyzer.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/selectvalues/SelectValuesStepAnalyzerTest.java
=> [BACKLOG-22144] Fix for Select value step analyzer

api/src/main/java/org/pentaho/dictionary/DictionaryConst.java, api/src/main/java/org/pentaho/dictionary/MetaverseAnalyzers.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/jobentry/JobEntryAnalyzer.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/StepAnalyzer.java, api/src/main/java/org/pentaho/metaverse/api/model/BaseDatabaseResourceInfo.java
Related PRs:
https://github.com/pentaho-es/pdi-igc-lineage-plugin/pull/7
https://github.com/pentaho/big-data-plugin/pull/1496
=> [BACKLOG-25113] Add application jar path to spark submit step

api/src/main/java/org/pentaho/dictionary/DictionaryConst.java, api/src/main/java/org/pentaho/metaverse/api/model/BaseMetaverseBuilder.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/BaseRuntimeExtensionPoint.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/BaseRuntimeExtensionPointTest.java
Related PR:
https://github.com/pentaho-es/pdi-igc-lineage-plugin/pull/9
=> [BACKLOG-25245] IGC Plugin - Fix duplicate field handling

api/src/main/java/org/pentaho/dictionary/DictionaryConst.java, api/src/main/java/org/pentaho/metaverse/api/model/BaseMetaverseBuilder.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/BaseRuntimeExtensionPoint.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/BaseRuntimeExtensionPointTest.java
=> [SP-4636] IGC Plugin - Fix duplicate field handling

api/src/main/java/org/pentaho/dictionary/DictionaryConst.java, api/src/main/java/org/pentaho/dictionary/MetaverseAnalyzers.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/jobentry/JobEntryAnalyzer.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/StepAnalyzer.java, api/src/main/java/org/pentaho/metaverse/api/model/BaseDatabaseResourceInfo.java
=> [SP-4634] Add application jar path to spark submit step

core/src/main/java/org/pentaho/metaverse/analyzer/kettle/jobentry/JobEntryAnalyzerProvider.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/StepAnalyzerProvider.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/jobentry/JobEntryAnalyzerProviderTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/StepAnalyzerProviderTest.java
=> [SP-4660] Exception when pentaho.metaverse.cfg file is changed

core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/singlethreader/SingleThreaderStepAnalyzer.java, core/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Reverts pentaho/pentaho-metaverse#517
=> Revert "[SP-4733] Backport of BACKLOG-25980 - [BACKLOG-25980] Minor fix to Si…"

api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/DatabaseConnectionAnalyzer.java, core/src/it/java/org/pentaho/metaverse/frames/DatasourceNode.java, core/src/it/java/org/pentaho/metaverse/step/TableOutputValidationIT.java, core/src/it/resources/repo/table-output-validation/table_io_bogus_db_fields_unchecked/table_io_bogus_db_fields_unchecked.ktr
@kcruzada @pvale @jlien @svigneri
=> [BACKLOG-26470] Adding variable replacement to connection details within the DatabaseConnectionAnalyzer

api/src/main/java/org/pentaho/metaverse/api/IMetaverseConfig.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/KettleAnalyzerUtil.java, api/src/main/resources/org/pentaho/metaverse/api/messages/messages.properties, core/src/it/java/org/pentaho/metaverse/MetaverseValidationDedupIT.java, core/src/it/java/org/pentaho/metaverse/MetaverseValidationSkipDedupIT.java, core/src/it/java/org/pentaho/metaverse/step/MappingAnalyzerValidationIT.java, core/src/it/java/org/pentaho/metaverse/step/SimpleMappingAnalyzerValidationIT.java, core/src/it/java/org/pentaho/metaverse/step/StepAnalyzerValidationIT.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/BaseRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/jobentry/job/JobJobEntryAnalyzer.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/jobentry/transjob/TransJobEntryAnalyzer.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/jobexecutor/JobExecutorStepAnalyzer.java, core/src/main/java/org/pentaho/metaverse/impl/MetaverseConfig.java, core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, core/src/main/resources/com/pentaho/metaverse/messages/messages.properties, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPointTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPointTest.java
Additionally fixed some resource messages, improved logging and added missing paths
=> [BACKLOG-26820] Allow fine grained control on the creating of graphml files

api/src/main/java/org/pentaho/dictionary/DictionaryHelper.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/AnnotationDrivenStepMetaAnalyzer.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/Metaverse.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/README.md, api/src/test/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/AnnotationDrivenStepMetaAnalyzerTest.java
Implementing an annotation driven analyzer to simplify lineage
definition.
https://jira.pentaho.com/browse/BACKLOG-26922
=> [BACKLOG-26922] MQTT Producer - Implement Kettle Lineage

api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/AnnotatedClassField.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/AnnotatedClassFields.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/AnnotationDrivenStepMetaAnalyzer.java, api/src/test/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/AnnotatedClassFieldsTest.java, api/src/test/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/AnnotationDrivenStepMetaAnalyzerTest.java
Enhancing AnnotationDrivenStepMetaAnalyzer to support @InjectionDeep
https://jira.pentaho.com/browse/BACKLOG-27217
=> [BACKLOG-27217] JMS Producer - Implement Kettle Lineage

core/pom.xml, sample/pom.xml
=> [BACKLOG-27567] Centralize org.osgi dependencies management

api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/AnnotatedClassFields.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/AnnotationDrivenStepMetaAnalyzer.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/Metaverse.java, api/src/main/resources/org/pentaho/metaverse/api/messages/messages.properties, api/src/test/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/AnnotationDrivenStepMetaAnalyzerTest.java
linking and streaming consumer resource input.
=> [BACKLOG-26935] Updates to annotation analyzer to accomodate subtrans

api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/SubtransAnalyzer.java, api/src/main/resources/org/pentaho/metaverse/api/messages/messages.properties
values from has other steps after it in the subtrans.
=> [BACKLOG-27645] Refactor code, handle the case where the step to return

api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/AnnotationDrivenStepMetaAnalyzer.java, api/src/test/java/org/pentaho/metaverse/api/analyzer/kettle/annotations/AnnotationDrivenStepMetaAnalyzerTest.java
=> [BACKLOG-27601] Only load stream fields once when called by

api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/KettleAnalyzerUtil.java
FILENAME specification method, but the trans objects are stored in a
repository.
=> [BACKLOG-27667] Handle the case where a step with mapping meta uses the

core/pom.xml, web/pom.xml
Needs https://github.com/pentaho/maven-parent-poms/pull/109.
@graimundo
=> [BACKLOG-27565] Centralize CXF dependency version

api/pom.xml, core/pom.xml, pom.xml
Needs https://github.com/pentaho/maven-parent-poms/pull/111
@graimundo
=> [BACKLOG-27566] Centralize SLF4J dependency

api/src/test/java/org/pentaho/dictionary/DictionaryHelperTest.java, core/pom.xml, core/src/it/java/org/pentaho/metaverse/BaseMetaverseValidationIT.java, core/src/it/java/org/pentaho/metaverse/JsonLineageIT.java, core/src/it/java/org/pentaho/metaverse/MetaverseValidationDedupIT.java, core/src/it/java/org/pentaho/metaverse/MetaverseValidationIT.java, core/src/it/java/org/pentaho/metaverse/MetaverseValidationSkipDedupIT.java, core/src/it/java/org/pentaho/metaverse/client/LineageClientIT.java, core/src/it/java/org/pentaho/metaverse/step/SingleThreaderStepAnalyzerValidationIT.java, core/src/it/java/org/pentaho/metaverse/step/StepAnalyzerValidationIT.java
- add mongo dependencies
- register core-plugin step
=> [CLEANUP][TEST] fix broken metaverse integration tests

api/src/test/java/org/pentaho/dictionary/DictionaryHelperTest.java, core/pom.xml, core/src/it/java/org/pentaho/metaverse/BaseMetaverseValidationIT.java, core/src/it/java/org/pentaho/metaverse/JsonLineageIT.java, core/src/it/java/org/pentaho/metaverse/MetaverseValidationDedupIT.java, core/src/it/java/org/pentaho/metaverse/MetaverseValidationIT.java, core/src/it/java/org/pentaho/metaverse/MetaverseValidationSkipDedupIT.java, core/src/it/java/org/pentaho/metaverse/client/LineageClientIT.java, core/src/it/java/org/pentaho/metaverse/step/SingleThreaderStepAnalyzerValidationIT.java, core/src/it/java/org/pentaho/metaverse/step/StepAnalyzerValidationIT.java
Reverts pentaho/pentaho-metaverse#606
=> Revert "[CLEANUP][TEST] fix broken metaverse integration tests"

api/src/main/java/org/pentaho/metaverse/api/model/DbcResourceInfo.java, api/src/main/java/org/pentaho/metaverse/api/model/ExternalResourceInfoFactory.java, api/src/main/java/org/pentaho/metaverse/api/model/OCIResourceInfo.java, api/src/test/java/org/pentaho/metaverse/api/model/ExternalResourceInfoFactoryTest.java, api/src/test/java/org/pentaho/metaverse/api/model/OCIResourceInfoTest.java
Based on https://github.com/pentaho/pentaho-metaverse/pull/532
Tested on windows 10 env connecting to a Oracle 11g
@pentaho-lmartins
=> [PDI-15431] Bug of Database Connection (Oracle OCI)

api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/KettleAnalyzerUtil.java
=> [BACKLOG-35111] Decode URI special characters from file path URIs to

api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/KettleAnalyzerUtil.java, api/src/test/java/org/pentaho/metaverse/api/analyzer/kettle/KettleAnalyzerUtilTest.java
@smmribeiro @bcostahitachivantara @moraesvc
=> [PDI-18930] JSON Input Step Performance Degradation and Memory Leak

core/pom.xml, pom.xml
[BACKLOG-36063] - added pdi-plugins dependency
=> [BACKLOG-36063] - added pdi-plugins dependency

core/pom.xml, pom.xml
Reverts pentaho/pentaho-metaverse#666
=> Revert "[BACKLOG-36063] - added pdi-plugins dependency"

core/pom.xml
this is for the backporting from the original commit - fa1ef381a2d13cb5087bf1eedc8e5a75f7abe9ef
=> [PPP-4654] Get commons-io version from parent pom

api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/ExternalResourceCache.java, pom.xml, web/pom.xml, web/src/main/java/org/pentaho/metaverse/service/AnalyzerInfoService.java, web/src/main/java/org/pentaho/metaverse/service/LineageStreamingOutput.java, web/src/main/java/org/pentaho/metaverse/service/MetaverseService.java, web/src/test/java/org/pentaho/metaverse/service/AnalyzerInfoServiceTest.java, web/src/test/java/org/pentaho/metaverse/service/MetaverseServiceTest.java
[BACKLOG-42751]-Upgrading Java EE WS RS to Jakarta EE WS RS in pentaho-metaverse
[BACKLOG-42751]: https://hv-eng.atlassian.net/browse/BACKLOG-42751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-42751]-Upgrading Java EE WS RS to Jakarta EE WS RS in pentaho-metaverse

core/pom.xml, core/src/it/java/org/pentaho/metaverse/BaseMetaverseValidationIT.java, core/src/it/java/org/pentaho/metaverse/JsonLineageIT.java, core/src/it/java/org/pentaho/metaverse/MetaverseValidationIT.java, core/src/it/java/org/pentaho/metaverse/analyzer/kettle/ExternalResourceConsumerIT.java, core/src/it/java/org/pentaho/metaverse/client/LineageClientIT.java, core/src/it/java/org/pentaho/metaverse/graph/MetaverseReaderIT.java, core/src/it/resources/repo/process all tables/Get list of tables.ktr, core/src/it/resources/repo/process all tables/Process all tables.kjb, core/src/it/resources/repo/process all tables/Process one table.kjb, core/src/it/resources/repo/process all tables/Process one table.ktr, core/src/it/resources/repo/process all tables/set variables.ktr, core/src/it/resources/repo/samples/file_to_table.ktr
The fixes for these 2 tests are solely the changes to the `ktr` and `kjb` files, the remaining changes are other minor fixes
=> test: fix the JsonLineageIT.testFileToTableJsonSerialize and ExternalResourceConsumerIT.testExternalResourceConsumer tests

.gitignore, core/src/site/site.xml
=> fix[BACKLOG-43745]: remove site.xml due to the upgrade of the project-info-reports plugin

core/pom.xml, web/pom.xml
[BACKLOG-45596]-Upgrade JDK properties from 11 to 17
[BACKLOG-45596]: https://hv-eng.atlassian.net/browse/BACKLOG-45596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-45596]-Upgrade JDK properties from 11 to 17
