core/src/main/java/org/pentaho/metaverse/analyzer/kettle/JobAnalyzer.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/jobentry/transjob/TransJobEntryAnalyzer.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPointTest.java
while running samples.
JobMeta doesn't have activated parameters by the time the analyzer(s) are called, and may not have the same values as its parent Job, so we need to copy them to the JobMeta before starting, and re-activate them once finished. This enables us to use environmentSubstitute to get at things like the executed transformation filename, if a parameter is used.
This came up while running the samples with lineage turned on.
=> [BACKLOG-4123] Fixed problem with use of JobMeta.environmentSubstitute

core/src/it/resources/repo/validation/exec_job.ktr, core/src/it/resources/solution/system/pentahoObjects.spring.xml, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobLineageHolderMap.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/entry/JobEntryExternalResourceConsumerListener.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/entry/JobEntryExternalResourceListener.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransLineageHolderMap.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/step/StepExternalConsumerRowListener.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/step/StepExternalResourceConsumerListener.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/jobexecutor/JobExecutorStepAnalyzer.java, core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobLineageHolderMapTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPointTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/entry/JobEntryExternalResourceConsumerListenerTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/entry/JobEntryExternalResourceListenerTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransLineageHolderMapTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPointTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/step/StepExternalConsumerRowListenerTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/step/StepExternalResourceConsumerListenerTest.java
Did some refactoring for the LineageHolders, also moved job/transFinished logic out into a thread, so as not to impact the performance of the job/trans.
Note the result row fields aren't created, there is no need until we have field-level lineage in jobs (see BACKLOG-3671)
=> [BACKLOG-2632] Implement custom metaverse step analyzer for Job Executor

core/src/it/java/org/pentaho/metaverse/MetaverseValidationIT.java, core/src/it/resources/repo/samples/file_to_table.ktr, core/src/it/resources/repo/validation/file_to_table.ktr
Fixes two integration test failures by changing references to the old
TFI to match the correct step ID for it.  Leaves the package names
alone.
=> [BACKLOG-5070] Lineage analyzer fixes for old and new Text File Input steps

core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransExtensionPointUtil.java
This was causing the auto-optimizations for Data Services to not be found when a new transformation was created in a repository and a Data Service was added.
The fix is simply to check whether it has a filename (if in local mode) or a PathAndName (if in repo mode)
=> [BACKLOG-5180] Add support for repo-based lineage at design time (in Spoon)

core/pom.xml, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/BaseRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobLineageHolderMap.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransLineageHolderMap.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPoint.java, core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, core/src/main/resources/OSGI-INF/blueprint/pdi-plugins.xml, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/BaseRuntimeExtensionPointTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPointTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPointTest.java
Had to do a couple of things to get the runtime lineage fully disabled:
- Add the property as specified in BACKLOG-5180, along with setter methods (and unit tests)
- Move the check for "is preview or is disabled" to the TransRuntimeExtensionPoint callback, this prevents lineage from adding a Trans listener to collect lineage
- Changed the Lineage maps to use soft references for keys (using Guava's MapMaker), this prevents us from keeping Trans references around when they are finished (so they can be garbage collected, instead of causing a memory leak)
- Added/updated unit tests
=> [BACKLOG-5308] Disable runtime lineage by default

api/src/main/java/org/pentaho/dictionary/DictionaryConst.java, api/src/test/java/org/pentaho/metaverse/api/MetaverseLogicalIdGeneratorTest.java
- adding "databaseName" to the LogiclaIdGenerator for JDBC node
- new unit test.
=> [PDI-14888] Data Lineage is creating wrong connection information

core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzer.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzerTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/transexecutor/TransExecutorStepAnalyzerTest.java
=> [SP-2656] Backport of PDI-14959 - Data Lineage: Table Output step analyzer does not add default fields to the lineage output (6.1 Suite)

core/pom.xml, web/pom.xml
The fix is needed due to using java 1.8, and incompatibility of asm old version (is used by jersey) reading new java 1.8 features 
The following scope of repositories is upgraded(except webdetails): The list is sorted in the order of build team runs
https://github.com/pentaho/pentaho-reporting
https://github.com/pentaho/mondrian
https://github.com/pentaho/pentaho-kettle
https://github.com/pentaho/pentaho-mondrianschemaworkbench-plugins
https://github.com/pentaho/pentaho-platform
https://github.com/webdetails/cpf
https://github.com/pentaho/pentaho-metaverse
https://github.com/pentaho/pdi-platform-utils-plugin
https://github.com/pentaho/pentaho-data-profiling
https://github.com/pentaho/data-access
https://github.com/pentaho/big-data-plugin
https://github.com/pentaho/pentaho-data-refinery …
=> [BACKLOG-8388] - Upgrade Jersey to 1.19.1 across the suite for Java 8 compatibility

core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPoint.java
The execution order was wrong - rearranged.
=> [PDI-15601] Enabling lineage.execution.runtime Leads to Unexpected Results when Executing jobs as Output of Previous Transformation

api/src/main/java/org/pentaho/metaverse/api/IMetaverseConfig.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/KettleAnalyzerUtil.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/BaseStepExternalResourceConsumer.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/ExternalResourceStepAnalyzer.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/IStepExternalResourceConsumer.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/StepAnalyzer.java, api/src/main/java/org/pentaho/metaverse/api/model/BaseResourceInfo.java, api/src/test/java/org/pentaho/metaverse/api/analyzer/kettle/step/ConnectionExternalResourceStepAnalyzerTest.java, api/src/test/java/org/pentaho/metaverse/api/analyzer/kettle/step/ExternalResourceStepAnalyzerTest.java, core/src/it/java/org/pentaho/metaverse/MetaverseValidationIT.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/impl/MetaverseConfig.java, core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPointTest.java
Also adding the "lineage.resolve.external.resources" config property for the metaverse osgi plugin and fixing some metaverse integration tests that were failing on windows.
Related pentaho-kettle PR: https://github.com/pentaho/pentaho-kettle/pull/5154
@pentaho/r2d2
=> [BACKLOG-21736] Adding input files for the case when JSON Input step file name is expressed in a field

api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/BaseStepExternalResourceConsumer.java, api/src/test/java/org/pentaho/metaverse/api/analyzer/kettle/step/BaseStepExternalResourceConsumerTest.java
Discovered this today. The change has no functional impact, and this "bug" doesn't affect current functionality, but that's only by luck. The implementation needs to be updated to be "correct".
Related PR: https://github.com/pentaho/pentaho-kettle/pull/5200
@pentaho/r2d2
=> [BACKLOG-21738][CLEANUP][TEST] Additional minor changes and added unit tests

core/src/it/java/org/pentaho/metaverse/MetaverseValidationIT.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobRuntimeExtensionPoint.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPoint.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransformationRuntimeExtensionPointTest.java
This ensures that all run-time initialization (including variable initialization) are complete before the analyzers start running.
Additionally, I fixed a few previously failing integration tests - these tests were failing due to unrelated changes made previously by others, but the test failures were only exposed now because the integration tests do not run as part of the nightly build
=> [BACKLOG-24278] Moving analyzer start up to the end of the ktr/kjb execution

api/pom.xml, api/src/main/java/org/pentaho/dictionary/DictionaryConst.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/jobentry/JobEntryAnalyzer.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/step/StepAnalyzer.java, api/src/main/java/org/pentaho/metaverse/api/model/BaseMetaverseBuilder.java, core/src/it/java/org/pentaho/metaverse/MetaverseValidationDedupIT.java, core/src/it/java/org/pentaho/metaverse/MetaverseValidationDefaultIT.java, core/src/it/java/org/pentaho/metaverse/MetaverseValidationIT.java, core/src/it/java/org/pentaho/metaverse/frames/FramedMetaverseNode.java, core/src/it/java/org/pentaho/metaverse/frames/RootNode.java, core/src/it/java/org/pentaho/metaverse/frames/TextFileInputNode.java, core/src/it/resources/repo/validation/file_to_table.ktr, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/streamlookup/StreamLookupStepAnalyzer.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/tableinput/TableInputStepAnalyzer.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzer.java, core/src/main/java/org/pentaho/metaverse/graph/BaseGraphWriter.java, core/src/main/java/org/pentaho/metaverse/graph/GraphCsvWriter.java, core/src/main/java/org/pentaho/metaverse/graph/GraphMLWriter.java, core/src/main/java/org/pentaho/metaverse/impl/MetaverseConfig.java, core/src/main/java/org/pentaho/metaverse/impl/VfsLineageWriter.java, core/src/main/java/org/pentaho/metaverse/util/MetaverseUtil.java, core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzerTest.java, pom.xml, web/pom.xml
In order to implement field level lineage in IGC, some changes needed to be made to the graph produces by the metaverse project. These changes included adding directly "contains" links from external resources to their fields and de-duplicating fields from a step that has more than one target step.
Additional changes:
- Fixed the table input step which lost the SQL query; igc used to grab it with roundabout logic that was removed, not the property is directly on the step node and shows in igc through a generic mechanism that displays all step properties in the header section
- made a change so that fields from all input steps (if more than one) are included and graphml and linked to the target step; this used to not be the case, only fields from the first encountered input step would be …
=> [BACKLOG-25381] Adding field level lineage support for file fields to IGC

api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/ExternalResourceCache.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/KettleAnalyzerUtil.java, api/src/test/java/org/pentaho/metaverse/api/analyzer/kettle/ExternalResourceCacheTest.java, api/src/test/java/org/pentaho/metaverse/api/analyzer/kettle/KettleAnalyzerUtilTest.java, core/src/main/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransLineageHolderMap.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobLineageHolderMapTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransLineageHolderMapTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/fileinput/text/TextFileInputStepAnalyzerTest.java, core/src/test/resources/com/pentaho/metaverse/messages/messages.properties
The previous implementation did not account for the fact that the same resources might be re-used by multiple transformations running at the same time, and the cache was being cleared prematurely. Additionally, the map would occasionally get cleared (possibly through GC?)
=> [BACKLOG-26731] Additional changes to allow running sub-transformations that read files from field

core/src/main/java/org/pentaho/metaverse/impl/VfsLineageWriter.java, core/src/test/java/org/pentaho/metaverse/impl/VfsLineageWriterTest.java
The lineage graphml path is determined in part by the trans name,
which in the case of temporary data service ktrs used by DET,
are not necessarily valid for a filename.
Added a safeguard to fall back to an "unknown" name whenever
a non-resolvable name is encountered.
https://jira.pentaho.com/browse/BACKLOG-28956
=> [BACKLOG-28956]  Errors with DET when Lineage is enabled

core/pom.xml
@pentaho/tatooine @pentaho-lmartins @wseyler 
* [PDI-17794] Removed version references due to maven-parent-poms controlling that aspect
This pull request is part of a series of pull requests:
- https://github.com/pentaho/maven-parent-poms/pull/137
- https://github.com/pentaho/adaptive-execution-layer/pull/3
- https://github.com/pentaho/big-data-plugin/pull/1682
- https://github.com/webdetails/cdf/pull/1075
- https://github.com/pentaho/commons-ee/pull/1
- https://github.com/webdetails/cpf/pull/144
- https://github.com/webdetails/cpk/pull/82
- https://github.com/pentaho/data-access/pull/1060
- https://github.com/pentaho/maven-project-archetypes/pull/16
- https://github.com/pentaho/maven-project-archetypes-ee/pull/35
- https://github.com/pentaho/modeler/pull/356
- …
=> [PDI-17794] Warnings in Spoon console due to wrong version of log4j

core/src/it/java/org/pentaho/metaverse/MetaverseValidationIT.java, core/src/it/java/org/pentaho/metaverse/analyzer/kettle/ExternalResourceConsumerIT.java, core/src/it/resources/repo/process all tables/save list of all result files.ktr, core/src/it/resources/repo/samples/customers-100.txt
PART2 ExternalResourceConsumerIT.testExternalResourceConsumer
-  adding customers-100.txt
-  fixed ktr text file output step relative file path
Note:
still integration tests failing: http://thanos.pentaho.net/job/9.0/job/it-snapshot/148/testReport/
There are 6 failing tests
most recent isolated execution, shows all tests passing for this commit: http://thanos.pentaho.net/job/9.0/job/it-snapshot-jobs/job/metaverse-plugin/255/
However, the execution of other projects integration tests effect the tests in metaverse.
This PR should address:
/ metaverse-plugin / org.pentaho.metaverse.analyzer.kettle.ExternalResourceConsumerIT.testExternalResourceConsumer[src/it/resources/repo/process all tables/Process all tables.kjb]
/ metaverse-plugin / …
=> [CLEANUP][TEST] fix broken metaverse integration tests

core/pom.xml, core/src/main/java/org/pentaho/metaverse/util/VfsDateRangeFilter.java
This reverts commit 2f8b20dfccc15b9ed71fa5b9d9ff41cfa2809f6f, reversing
changes made to f41474c5b8c694daee9ea05773d02024ddd933b7.
This Revert PR is part of a series:
- https://github.com/pentaho/maven-parent-poms/pull/229
- https://github.com/pentaho/apache-vfs-browser/pull/62
- https://github.com/pentaho/big-data-plugin/pull/2040
- https://github.com/webdetails/cpk/pull/87
- https://github.com/pentaho/data-access/pull/1091
- https://github.com/pentaho/mondrian/pull/1202
- https://github.com/pentaho/pdi-jms-plugin/pull/76
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/104
- https://github.com/pentaho/pdi-plugins-ee/pull/174
- https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/84
- https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/53
- …
=> Revert "Merge pull request #620 from gryphendowre/SP-5370"

api/pom.xml, api/src/main/java/org/pentaho/metaverse/api/IMetaverseConfig.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/ExternalResourceCache.java, api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/KettleAnalyzerUtil.java, api/src/test/java/org/pentaho/metaverse/api/analyzer/kettle/ExternalResourceCacheTest.java, core/src/main/java/org/pentaho/metaverse/impl/MetaverseConfig.java, core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/job/JobLineageHolderMapTest.java, core/src/test/java/org/pentaho/metaverse/analyzer/kettle/extensionpoints/trans/TransLineageHolderMapTest.java
- removed inconsequential transMap variable, TransValues defined
in ExternalResourceCache is not used externally
- modified caching with eviction by time
=> [PDI-18657] Memory leak when customer executes jobs on the server

core/src/test/java/org/pentaho/metaverse/impl/model/kettle/json/JobEntryBaseJsonSerializerTest.java
Backporting the change, already in master under [pentaho-metaverse#686](https://github.com/pentaho/pentaho-metaverse/pull/686), that fixes the failing 'org.pentaho.metaverse.impl.model.kettle.json.JobEntryBaseJsonSerializerTest.testWriteRepoAttributes' unit test:
@renato-s @andreramos89 @befc @joana-fb @miguelappleton
=> [TEST] Fixing testWriteRepoAttributes method argument matchers

api/pom.xml, assemblies/plugin/src/assembly/assembly.xml, core/pom.xml
- [PPP-4895] Exclude jettison in metaverse-plugin assembly.xml
- [PPP-4895] Exclude jettison in pentaho-metaverse plugin
[PPP-4895]: https://hv-eng.atlassian.net/browse/PPP-4895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PPP-4895]: https://hv-eng.atlassian.net/browse/PPP-4895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SP-6635] Backport of PPP-4895 - Vulnerable Component: Jettison

api/pom.xml, web/pom.xml
[BACKLOG-43938]-Fixing test1 pipeline test failures running on JDK21
[BACKLOG-43938]: https://hv-eng.atlassian.net/browse/BACKLOG-43938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43938]-Fixing test1 pipeline test failures running on JDK21
